FROM python:%%PLACEHOLDER%%

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ARG REQUIREMENTS_FILE=requirements.txt
ONBUILD COPY $REQUIREMENTS_FILE /usr/src/app/
ONBUILD RUN pip install --no-cache-dir -r $REQUIREMENTS_FILE

ONBUILD COPY . /usr/src/app
